# Generated by Django 5.0.7 on 2024-07-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('at_reason', models.CharField(max_length=30, verbose_name='Motivo')),
                ('at_school_enrollment', models.CharField(max_length=30, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
    ]
