# Generated by Django 5.0.7 on 2024-08-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0006_rename_furniture_classroom_cm_furniture_and_more'),
        ('solicitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('fk_classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salas.classroom', verbose_name='Sala')),
                ('fk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.applicant', verbose_name='Nombre solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
