# Generated by Django 5.0.6 on 2024-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=30)),
            ],
        ),
    ]
