# Generated by Django 5.0.6 on 2024-08-13 00:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario', '0004_alter_schedule_se_day'),
        ('salas', '0007_classroom_cm_roof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('rt_objetos', models.CharField(blank=True, choices=[('microphones', 'micrófonos'), ('podium', 'estrado'), ('presidio', 'presidio'), ('proyector', 'projector')], max_length=11, null=True, verbose_name='extras')),
                ('request_time', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='Hora de la solicitud')),
                ('classroom_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salas.classroom', verbose_name='Sala')),
                ('rt_horario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario.schedule')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
