# Generated by Django 5.0.7 on 2024-08-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='fk_name',
            new_name='applicant_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='fk_classroom',
            new_name='classroom_name',
        ),
    ]
