# Generated by Django 5.0.6 on 2024-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_solicitudes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
