# Generated by Django 5.0.6 on 2024-08-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_alter_schedule_se_day'),
        ('solicitud', '0002_rename_fk_name_request_applicant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.AddField(
            model_name='request',
            name='rt_horario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario.schedule'),
        ),
    ]
