# Generated by Django 5.0.6 on 2024-08-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_request_applicant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='applicant_name',
            field=models.CharField(max_length=30, verbose_name='nombre_de_solicitante'),
        ),
    ]
