# Generated by Django 5.0.7 on 2024-08-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0006_remove_schedule_se_classroom'),
        ('solicitud', '0003_alter_request_applicant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rt_horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario.schedule'),
        ),
    ]
