# Generated by Django 5.0.7 on 2024-08-14 16:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_request_rt_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rt_objetos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('microphones', 'micrófonos'), ('podium', 'estrado'), ('presidio', 'presidio'), ('proyector', 'projector')], max_length=11, null=True, verbose_name='extras'),
        ),
    ]
