# Generated by Django 5.0.6 on 2024-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_rename_solicitudes_requests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
