# Generated by Django 5.0.6 on 2024-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_rename_requests_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=30, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='request',
            name='school_enrollment',
            field=models.CharField(max_length=30, verbose_name='Matricula'),
        ),
    ]
