# Generated by Django 5.0.7 on 2024-08-17 20:17

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_alter_classroom_horarios'),
        ('solicitud', '0005_alter_request_rt_objetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='classroom_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salones', to='salas.classroom', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='request',
            name='rt_objetos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('microphones', 'micrófonos'), ('podium', 'estrado'), ('presidio', 'presidio'), ('proyector', 'projector')], max_length=37, null=True, verbose_name='extras'),
        ),
    ]
