# Generated by Django 5.0.6 on 2024-08-18 04:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_alter_classroom_horarios'),
        ('solicitud', '0006_alter_request_classroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rt_dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='rt_horafin',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='horafinal'),
        ),
        migrations.AlterField(
            model_name='request',
            name='classroom_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salonespedi', to='salas.classroom', verbose_name='Sala'),
        ),
    ]
