# Generated by Django 5.0.7 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_request_rt_dia_request_rt_horafin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rt_descripcion',
            field=models.CharField(default='', max_length=150, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='request',
            name='rt_matricula',
            field=models.CharField(default='2022IDGS070', max_length=11, verbose_name='matricula_solicitante'),
        ),
    ]
