# Generated by Django 5.0.7 on 2024-08-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0009_alter_request_rt_matricula_alter_request_rt_objetos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objets',
            name='os_Peticion',
        ),
        migrations.AddField(
            model_name='objets',
            name='os_Peticion',
            field=models.ManyToManyField(to='solicitud.request', verbose_name='Peti_objetos'),
        ),
    ]
