# Generated by Django 5.0.7 on 2024-08-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0010_remove_objets_os_peticion_objets_os_peticion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objets',
        ),
    ]
