# Generated by Django 5.0.6 on 2024-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_day', models.CharField(max_length=20, verbose_name='dia')),
                ('se_start_time', models.TimeField(verbose_name='horario inicio')),
                ('se_end_time', models.TimeField(verbose_name='hora de finalizacion ')),
            ],
            options={
                'verbose_name': 'Horario de salon',
                'verbose_name_plural': 'Horarios de salones',
            },
        ),
    ]
