# Generated by Django 5.0.6 on 2024-08-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_schedule_se_classroom_alter_schedule_se_end_time'),
        ('salas', '0007_classroom_cm_roof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='se_classroom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='horario_de_salon', to='salas.classroom'),
        ),
    ]
