# Generated by Django 5.0.6 on 2024-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_alter_schedule_se_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='se_day',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=9, verbose_name='Día'),
        ),
    ]
