# Generated by Django 5.0.6 on 2024-08-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0005_remove_schedule_se_classroom_schedule_se_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='se_classroom',
        ),
    ]
