# Generated by Django 5.0.6 on 2024-06-26 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_salon_encargado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salon',
            new_name='Salones',
        ),
    ]
