# Generated by Django 5.0.6 on 2024-07-12 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_rename_salon_salones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('bg_description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('furniture', models.CharField(max_length=15, verbose_name='Moviliario')),
                ('cm_description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('rm_description', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de sala',
                'verbose_name_plural': 'Tipos de sala',
            },
        ),
        migrations.DeleteModel(
            name='Edificio',
        ),
        migrations.AddField(
            model_name='classroom',
            name='cm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.roomtype'),
        ),
        migrations.DeleteModel(
            name='Salones',
        ),
        migrations.DeleteModel(
            name='TipoSala',
        ),
    ]
