# Generated by Django 5.0.7 on 2024-07-19 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_building_classroom_roomtype_delete_edificio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cm_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.roomtype', verbose_name='Tipo de sala'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
