# Generated by Django 5.0.7 on 2024-07-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_alter_classroom_cm_type_alter_classroom_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='furniture',
            new_name='cm_furniture',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='manager',
            new_name='cm_manager',
        ),
    ]
