# Generated by Django 5.0.6 on 2024-08-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_rename_furniture_classroom_cm_furniture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='cm_roof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edificio', to='salas.building'),
        ),
    ]
