# Generated by Django 5.0.6 on 2024-08-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_classroom_cm_roof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='rm_description',
            field=models.CharField(max_length=150, verbose_name='Descripción_tipo'),
        ),
    ]
