# Generated by Django 5.0.6 on 2024-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0006_remove_schedule_se_classroom'),
        ('salas', '0008_alter_roomtype_rm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='horarios',
            field=models.ManyToManyField(to='horario.schedule'),
        ),
    ]
